version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: myprojectuser
      POSTGRES_PASSWORD: myprojectpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://myprojectuser:myprojectpassword@postgres:5432/myproject
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - /app/node_modules
      - ./frontend/app:/app
    # ports:
    #   - "8080:5173"
    environment:
      - VUE_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network

  frontend-admin:
    build: ./frontend-admin
    command: npm run dev
    volumes:
      - /app/node_modules
      - ./frontend-admin/app:/app
    # ports:
    #   - "8081:5173"
    environment:
      - VUE_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./frontend/dist:/usr/share/nginx/html/main  # 主前端静态文件
      # - ./frontend-admin/dist:/usr/share/nginx/html/admin # 管理后台静态文件
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge