version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: myprojectuser
      POSTGRES_PASSWORD: myprojectpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://myprojectuser:myprojectpassword@postgres:5432/myproject
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: ./frontend
    command: npm run serve
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/app/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge