<template>
  <el-dialog :model-value="modelValue" @close="close" title="Terms of Service" width="750px">
    <div class="terms-icon">
      <i class="el-icon-document"></i>
    </div>
    <div class="terms-content">
      <p>Welcome! Before you join our platform as a Volunteer or Non-Profit Organization (NPO), please review our Terms of Service.</p>
      
      <p>This agreement governs your use of our website, which connects volunteers with NPOs. By registering, you agree to use the platform responsibly and lawfully.</p>
      
      <div class="section">
        <h2>Key Points for Your Review</h2>
        
        <h3>For Volunteers</h3>
        <p>You understand that opportunities are user-generated by NPOs. We do not screen all listings and you are responsible for assessing the suitability and legitimacy of any opportunity before participating.</p>
        
        <h3>For NPOs</h3>
        <p>You warrant that you are a legitimate organization and are solely responsible for the accuracy of your postings, including the description, dates, and required skills. You agree to manage volunteers professionally and ensure a safe environment.</p>
        
        <h3>User Conduct</h3>
        <p>You agree not to post harmful, fraudulent, or offensive content. You will not misuse other users' personal information.</p>
        
        <h3>Intellectual Property</h3>
        <p>Content you post remains yours, but you grant us a license to display and distribute it on the platform.</p>
        
        <h3>Limitation of Liability</h3>
        <p>We provide the platform "as is." We are not liable for any interactions between users, or for any damages arising from the use of posted opportunities.</p>
      </div>
      
      <div class="agreement">
        <p>By clicking "I Agree," you acknowledge you have read, understood, and agree to be bound by these terms.</p>
      </div>
      
      <div class="update-date">
        Last Updated: September 15, 2025
      </div>
    </div>
    
    <template #footer>
      <span class="dialog-footer">
        <el-button type="primary" @click="close">
          I Agree
        </el-button>
      </span>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
defineProps<{ modelValue: boolean }>()
const emit = defineEmits(['update:modelValue'])

// Close the dialog
function close() {
  emit('update:modelValue', false)
}
</script>

<style scoped>
.terms-icon {
  display: block;
  text-align: center;
  font-size: 48px;
  color: #409eff;
  margin-bottom: 15px;
}

.terms-content {
  max-height: 60vh;
  overflow-y: auto;
  padding: 0 15px;
  text-align: left;
  color: #333;
}

.terms-content h2 {
  color: #409eff;
  margin-top: 25px;
  margin-bottom: 18px;
  font-size: 1.5rem;
  font-weight: 600;
  padding-bottom: 8px;
  border-bottom: 2px solid #eaeef5;
}

.terms-content h3 {
  color: #606266;
  margin-top: 20px;
  margin-bottom: 12px;
  font-size: 1.25rem;
  font-weight: 500;
}

.terms-content p {
  line-height: 1.7;
  margin-bottom: 15px;
  font-size: 1rem;
}

.terms-content .section {
  background-color: #f9fafc;
  border-left: 4px solid #409eff;
  padding: 15px 20px;
  margin: 20px 0;
  border-radius: 0 8px 8px 0;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
}

.terms-content .agreement {
  background-color: #f0f7ff;
  border: 1px solid #c6e2ff;
  border-radius: 8px;
  padding: 15px 20px;
  margin: 25px 0;
  text-align: center;
  font-weight: 500;
}

/* Scrollbar styling */
.terms-content::-webkit-scrollbar {
  width: 10px;
}

.terms-content::-webkit-scrollbar-track {
  background: #f1f1f1;
  border-radius: 10px;
}

.terms-content::-webkit-scrollbar-thumb {
  background: #c0c4cc;
  border-radius: 10px;
  border: 2px solid #f1f1f1;
}

.terms-content::-webkit-scrollbar-thumb:hover {
  background: #a8acb5;
}

.dialog-footer {
  display: flex;
  justify-content: center;
  padding: 15px 20px 25px;
}

.dialog-footer .el-button {
  padding: 12px 30px;
  font-size: 16px;
  border-radius: 8px;
  transition: all 0.3s;
}

.update-date {
  text-align: center;
  margin-top: 25px;
  padding-top: 15px;
  border-top: 1px dashed #eaeef5;
  color: #909399;
  font-style: italic;
  font-size: 0.9rem;
}
</style>