name: 🚀 Test CI/CD Pipeline

on:
  pull_request:
    branches: [ "test" ]
    types: [opened, synchronize, reopened]
  push:
    branches: [ "test" ]

jobs:
  build-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Frontend
        run: cd frontend/app && npm install && npm run build
      - name: Build Admin Frontend
        run: cd frontend-admin/app && npm install && npm run build

  deploy-prod:
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Frontend
        run: cd frontend/app && npm install && npm run build
      - name: Build Admin Frontend
        run: cd frontend-admin/app && npm install && npm run build
      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.aliCloud }}
          script: |
            cd /home/project/Volunteer-webstie
            git reset --hard HEAD
            git pull origin main
            docker compose down
            docker compose up -d --build
            docker image prune -f
