"""
Django settings for volunteer_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from django.template.context_processors import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2e2y4b5)xeqyu4mbnqgry3ycn+xz$^2_j(hd7qalz#h=fubyn5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'backend', 'nginx']


# Application definition

INSTALLED_APPS = [
    'accounts.apps.AccountsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # 'npo',
    # 'visitor',
    # 'admin_app',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 定义了项目的根url配置，应该在core urls.py里面
ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'myproject',
        'USER': 'myprojectuser',
        'PASSWORD': 'myprojectpassword',
        'HOST': 'postgres',
        # 'NAME': 'postgres',  # 本地数据库连接test xjn
        # 'USER': 'postgres',
        # 'PASSWORD': '123456',
        # 'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# 所有静态文件（CSS、JavaScript、图片等）都通过以/static/开头的URL来访问
STATIC_URL = 'static/'
# 相关静态文件配置
# 开发环境：指定额外的静态文件目录
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
#     '', # 放入其他自定义目录 如/var/www/static/
# ]
# 生产环境： 收集静态文件的目标目录
# STATIC_ROOT = BASE_DIR / 'static' #AI和自动补全的代码
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 当运行collectstatic命令时，请将所有静态文件收集到项目根目录下的staticfiles（生产时自动创建？）文件夹中。

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# MEDIA_URL = '/media/';MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 暂时不需要media数据

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 解决数据库模型冲突（多个用户模型），指定自定义的用户模型
AUTH_USER_MODEL = 'accounts.Account'

# 配置REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # 根据需要调整权限
    ],
}
# 配置CORS允许前端访问
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vue开发服务器默认端口
    "http://127.0.0.1:5173",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://127.0.0.1:8081",
    "http://localhost:8081",
    "http://nginx:80"
]

# 允许携带Cookie
CORS_ALLOW_CREDENTIALS = True


